export const themes = ["corporate", "night", "aqua", "valentine"  ];
export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
export const EasyAppointments = {
  API_URL:"http://localhost/index.php/api/v1/",
  API_KEY: "Recliner0~Stinky~Decorated~Crook~Hydrant"
}
